<?php

return [
    'modes' => [
        'Text' => 'Text',
        'C#' => 'CSharp',
        'HTML' => 'HTML',
        'INI' => 'INI',
        'Java' => 'Java',
        'JavaScript' => 'JavaScript',
        'JSON' => 'JSON',
        'CSS' => 'CSS',
        'LESS' => 'LESS',
        'SASS' => 'SASS',
        'SCSS' => 'SCSS',
        'Lisp' => 'Lisp',
        'Lua' => 'Lua',
        'MySQL' => 'MySQL',
        'Pascal' => 'Pascal',
        'Perl' => 'Perl',
        'pgSQL' => 'pgSQL',
        'PHP' => 'PHP',
        'PHP_Laravel_blade' => 'PHP_Laravel_blade',
        'Python' => 'Python',
        'Ruby' => 'Ruby',
        'Rust' => 'Rust',
        'SQL' => 'SQL',
        'Swift' => 'Swift',
        'TSX' => 'TSX',
        'Twig' => 'Twig',
        'Typescript' => 'Typescript',
        'VBScript' => 'VBScript',
        'XML' => 'XML',
        'YAML' => 'YAML',
    ]
];
